### ISSUE TITLE
提案: SEOの設定をコンポーネント化する

### ISSUE THREAD

**Issue by RimlTempest** [mopeneko/blog#2]
SEOの設定をコンポーネント化することでページごとのSEO設定が行えたり長い設定等でコードの汚染を防げるのではないかと思ったので提案です！

実装例は #1 になります

**Comment by mopeneko** [comment]
Remixに切り替えることにしたので、同様のものをRemixにて実装します
その際実装例を参考にさせて頂きます

**Comment by mopeneko** [comment]
やっぱRemixやめた！

**Comment by RimlTempest** [comment]
ブログのISR対応したみたいだしRemixに置き換えるのいろいろめんどくさそうだと思ってた🤡
