### ISSUE TITLE
提案: SEOつながりでPWA対応する

### ISSUE THREAD

**Issue by RimlTempest** [mopeneko/blog#3]
PWA対応することでモバイルネイティブな操作が可能になる
ブログを見るユーザ層も鑑みるとモバイルアクセスが増加すると思うので対応することでSEO観点からもプラスになるしUXもよくなると思ったので提案です。

対応にはNext公式にも記載のある`Next-pwa`を用いる

#4 対応例はこちらです！

**Comment by mopeneko** [comment]
Remixにするので[こんな感じに](https://sergiodxa.com/articles/using-service-workers-with-remix)やろうと思います
